"""add token columns to run_steps

Revision ID: 70fc5bbaa77f
Revises: 7c4f78b2a7d4
Create Date: 2026-08-04 01:23:11.764009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fc5bbaa77f'
down_revision = '7c4f78b2a7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_steps', schema=None) as batch_op:
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')

    # ### end Alembic commands ###
