"""add user metadata fields and tickets table

Revision ID: f187970f2b6d
Revises: 70fc5bbaa77f
Create Date: 2026-08-12 22:07:19.394249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f187970f2b6d'
down_revision = '70fc5bbaa77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('requester_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('requester_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('requester_department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sla_minutes_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draft_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('draft_confidence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escalation_reason', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('role_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role_title')
        batch_op.drop_column('department')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('escalation_reason')
        batch_op.drop_column('draft_confidence')
        batch_op.drop_column('draft_reply')
        batch_op.drop_column('sla_minutes_remaining')
        batch_op.drop_column('channel')
        batch_op.drop_column('requester_department')
        batch_op.drop_column('requester_email')
        batch_op.drop_column('requester_name')
        batch_op.drop_column('ticket_number')

    # ### end Alembic commands ###
